[package]
name = "env_file_generator"
version = "0.1.0"
edition = "2018"

[lib]
path = "src/lib.rs"
crate-type = ["lib"]

[dependencies]
ic-cdk = "0.5.1"
ic-cdk-macros = "0.5.1"
serde = "1.0"
serde_json = "1.0.79"
str-macro = "1.0.0"