
/*
This file is automatically generated based on the environment set

File can be generated with the following commands:
    LOCAL: "ENV=local cargo test --test generate"
    DEVELOPMENT: "ENV=development cargo test --test generate"
    STAGING: "ENV=staging cargo test --test generate"
    PRODUCTION: "ENV=production cargo test --test generate"

    Note: If the local canister ids are not known yet, 
    the "dfx canister create --all --no-wallet" command should be ran
    to generate the local canister ids (.dfx/local/canister_ids.json)
*/

// These canisters are environment independent
pub const CYCLES_MANAGEMENT_CANISTER_ID: &str = "tfpzd-cqaaa-aaaam-qamia-cai";pub const DEVELOPMENT_MANAGEMENT_CANISTER_ID: &str = "mix2w-yqaaa-aaaal-qa2lq-cai";pub const STAGING_MANAGEMENT_CANISTER_ID: &str = "r3orl-tyaaa-aaaak-qaoba-cai";pub const PRODUCTION_MANAGEMENT_CANISTER_ID: &str = "ml5iu-4qaaa-aaaan-qahiq-cai";

// These canisters are environment dependent
pub const GROUP_MANAGEMENT_CANISTER_ID: &str = "feeig-haaaa-aaaak-aat5a-cai";pub const MANAGEMENT_CANISTER_ID: &str = "mix2w-yqaaa-aaaal-qa2lq-cai";pub const REPORT_CANISTER_ID: &str = "cp23e-7iaaa-aaaap-qahvq-cai";pub const STORAGE_MANAGEMENT_CANISTER_ID: &str = "qpoty-vaaaa-aaaam-qahtq-cai";pub const USER_CANISTER_ID: &str = "yfnxe-7qaaa-aaaag-aaieq-cai";

// These canisters are only used for the local deployment
pub const GROUP_CANISTER_ID: &str = "";pub const STORAGE_CANISTER_ID: &str = "";

// Settings to be specified per environment
pub const ENVIRONMENT: &str = "development";pub const MAX_GROUP_CANISTERS: usize = 10;pub const MAX_GROUP_CANISTERS_ENABLED: bool = true;pub const MAX_STORAGE_CANISTERS: usize = 1;pub const MAX_STORAGE_CANISTERS_ENABLED: bool = true;pub const MAX_REGISTERED_USERS: usize = 500;pub const MAX_REGISTERED_USERS_ENABLED: bool = true;